### ISSUE TITLE
test backticks

### ISSUE THREAD

**Issue by tmetz** [metztest/test-theme#41]
Testing

\`test text\`

test \`test text\` test again

**Comment by tmetz** [comment]
> `test text`

formatted with \<pre\>

**Comment by tmetz** [comment]
formatted with \\<pre\\>

**Comment by jjkennedy3** [comment]
test comment

**Comment by tmetz** [comment]
https://github.com/Shopify/bootsnap/compare/v1.7.7...v1.8.0#commitcomment-55503701

**Comment by tmetz** [comment]
https://github.com/metztest/test-theme/commit/fb9f6369d2704b3c9d922c1f0786eb26eb993675#r55938512
