### ISSUE TITLE
Bulleted list fun

### ISSUE THREAD

**Issue by tmetz** [metztest/test-theme#44]
Here is a bulleted list:

- item 1
- item 2
- item 3

Goodbye!

**Comment by tmetz** [comment]
Here is the quote reply from Chrome:



> Here is a bulleted list:
> 
> * item 1
> * item 2
> * item 3
> 
> Goodbye!

**Comment by tmetz2** [comment]
Here is the quote reply from Safari:



> Here is a bulleted list:
> 
> * item 1
> * item 2
> * item 3
> 
> Goodbye!

**Comment by tmetz2** [comment]
Here is the quote reply from 88.0.1 (64-bit):



> Here is a bulleted list:
> 
>     * item 1
> 
>     * item 2
> 
>     * item 3
> 
> 
> Goodbye!
