### ISSUE TITLE
More bulleted list fun

### ISSUE THREAD

**Issue by tmetz** [metztest/test-theme#45]
Here is a bulleted list:

- item 1
- item 2
- item 3

Goodbye!

**Comment by tmetz** [comment]
Quote reply from Chrome:



> Here is a bulleted list:
> 
> * item 1
> * item 2
> * item 3
> 
> Goodbye!

**Comment by tmetz2** [comment]
Quote reply from Safari:



> Here is a bulleted list:
> 
> * item 1
> * item 2
> * item 3
> 
> Goodbye!

**Comment by tmetz2** [comment]
Quote reply from Firefox 88.0.1 (64-bit):



> Here is a bulleted list:
> 
>     * item 1
> 
>     * item 2
> 
>     * item 3
> 
> 
> Goodbye!

**Comment by tmetz** [comment]
* bullet 1
  new line
  
* bullet 2

**Comment by tmetz** [comment]
test

**Comment by tmetz** [comment]
[![Discord](https://raw.githubusercontent.com/dahliaOS/.github/main/profile/assets/images/dark/Discord.svg)](https://dahliaos.io/discord#gh-dark-mode-only)

[![Discord](https://raw.githubusercontent.com/dahliaOS/.github/main/profile/assets/images/light/Discord.svg)](https://dahliaos.io/discord#gh-light-mode-only)


```

[![Discord](https://raw.githubusercontent.com/dahliaOS/.github/main/profile/assets/images/dark/Discord.svg)](https://dahliaos.io/discord#gh-dark-mode-only)

[![Discord](https://raw.githubusercontent.com/dahliaOS/.github/main/profile/assets/images/light/Discord.svg)](https://dahliaos.io/discord#gh-light-mode-only)

```

**Comment by tmetz** [comment]
<a href = "https://dahliaos.io/discord#gh-dark-mode-only"><img src = "https://raw.githubusercontent.com/dahliaOS/.github/main/profile/assets/images/dark/Discord.svg"></a>

<a href = "https://dahliaos.io/discord#gh-light-mode-only"><img src = "https://raw.githubusercontent.com/dahliaOS/.github/main/profile/assets/images/light/Discord.svg"></a>

```
<a href = "https://dahliaos.io/discord#gh-dark-mode-only"><img src = "https://raw.githubusercontent.com/dahliaOS/.github/main/profile/assets/images/dark/Discord.svg"></a>

<a href = "https://dahliaos.io/discord#gh-light-mode-only"><img src = "https://raw.githubusercontent.com/dahliaOS/.github/main/profile/assets/images/light/Discord.svg"></a>
```
